title: Octave Larose
author:
  # name: Octave Larose
  email: octave.larose@hotmail.com

description: >
  My own personal website, with my own personal views and random thoughts.

header_pages:
  - about.md

theme: minima
